# Generated by Django 6.0.1 on 2026-01-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="set",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A1", "Genetic Apex"),
                    ("A1a", "Mythical Island"),
                    ("A2", "Space-Time Smackdown"),
                    ("A2a", "Triumphant Light"),
                    ("A2b", "Shining Revelry"),
                    ("A3", "Celestial Guardians"),
                    ("A3a", "Extradimensional Crisis"),
                    ("A3b", "Eevee Grove"),
                    ("A4", "Wisdom of Sea and Sky"),
                    ("A4a", "Secluded Springs"),
                    ("A4b", "Deluxe Pack Ex"),
                    ("B1", "Mega Rising"),
                    ("B1a", "Crimson Blaze"),
                    ("B2", "Fantastical Parade"),
                    ("P-A", "Promo A"),
                    ("P-B", "Promo B"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="set",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A1", "Genetic Apex"),
                    ("A1a", "Mythical Island"),
                    ("A2", "Space-Time Smackdown"),
                    ("A2a", "Triumphant Light"),
                    ("A2b", "Shining Revelry"),
                    ("A3", "Celestial Guardians"),
                    ("A3a", "Extradimensional Crisis"),
                    ("A3b", "Eevee Grove"),
                    ("A4", "Wisdom of Sea and Sky"),
                    ("A4a", "Secluded Springs"),
                    ("A4b", "Deluxe Pack Ex"),
                    ("B1", "Mega Rising"),
                    ("B1a", "Crimson Blaze"),
                    ("B2", "Fantastical Parade"),
                    ("P-A", "Promo A"),
                    ("P-B", "Promo B"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
